openapi: '3.0.2'

info:
  version: "1.0"
  title: Check URL API

servers:
  - url: /

tags:
  - name: "CheckURL"
    description: "Endpoints for the check URL feature"

paths:
  /check:
    post:
      operationId: fm_url_checker.producer.api.post
      tags:
        - CheckURL
      description: Queue a new check URL job

      requestBody:
        description: "The URL to be checked"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/url'

      responses:
        201:
          description: Job queued successfully, returning the Job id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        400:
          description: Supplied data did not pass validation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

components:
  schemas:
    url:
      type: object
      properties:
        url:
          description: An RFC 3987 compliant URL.
          type: string

      required:
        - url

      example:
        url: http://example.com/path?param=val

    job:
      type: object
      properties:
        id:
          description: 32 char UUID
          type: string

      required:
        - id

      example:
        id: "46d5770c80734a17b0f3ce1a0096f618"

    error_response:
      type: object
      description: Problem details object [RFC 7807]
      properties:
        type:
          type: string
          description: "A URI reference that identifies the problem type."
        title:
          type: string
          description: "A short, human-readable summary of the problem type."
        status:
          type: number
          description: "The HTTP status code generated by the origin server for this occurrence of the problem"
        detail:
          type: string
          description: "A human-readable explanation specific to this occurrence of the problem."
        instance:
          type: string
          description: "A URI reference that identifies the specific occurrence of the problem."

      required:
        - type
        - title

      example:
        type: "fm/error/validation"
        title: "Data Validation"
        status: 400
        detail: "The supplied data was invalid, expected ..."
        instance: "fm/error/validation/url"
